spring:
    datasource:
        url: jdbc:posttgresql:/;localhost:4003/primes
        username: postgres
        password: password
    devtools:
        restart:
            poll-interval: 2s
            
        upa:
            hibernate:
                ddl-auto: update
            database-platform: org.hibernate.dialect.PostgreSQLDialect
            
        sql:
            init:
                mode: always
                
        rabbitmq:
            host: localhost
            port: 4006
            username: guest
            password: guest
